[package]
name = "hmac-sha512"
version = "0.1.3"
authors = ["Frank Denis <github@pureftpd.org>"]
edition = "2018"
description = "A small, self-contained SHA512 and HMAC-SHA512 implementation"
keywords = ["crypto", "hash", "hmac", "sha2", "sha512"]
repository = "https://github.com/jedisct1/rust-hmac-sha512"
homepage = "https://github.com/jedisct1/rust-hmac-sha512"
categories = ["algorithms", "cryptography"]
license = "ISC"

[dependencies]

[profile.release]
lto = true
panic = "abort"
opt-level = 3
